- name: Storage operations on VMAX
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  roles:
    - storage_group_role

  vars_prompt:
    - name: user_input
      prompt: |
        Please select an action:
        1. Create a storage group
        2. Create new volumes then add them to an existing Storage Group
        3. Add existing volumes to existing Storage Group
        4. List volumes of a Storage Group
        5. Modify Storage Group
        6. Delete Storage Group
      private: false
  vars_files:
    - vault.yml
