---
- name: Volume and storage operations on VMAX
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  roles:
   # - volume_role
    - storage_group_role

  vars:
    unispherehost: "10.118.128.103"  # IP address of the PowerMax system
    verifycert: false
    user: 'smc'  # Your username
    password: 'smc'  # Your password
    serial_no: '000297901660'
    sg_name: 'Edward_LNK_SG_001'
    ansible_python_interpreter: /root/pyu4v_env/bin/python3
    universion: 92
    vol_name: 'sarah_t1'  # we should ask the user for this but fr nw its hard-coded
    cap_unit: 'GB'
    vol_size: 2
    append_vol_id: true
    user_volume_name: "{{ user_volume_name }}"
  vars_prompt:
    - name: user_input
      prompt: |
        Please select an action:
        1. Create a storage group
        2. Create new volumes for existing Storage Group
        3. Add existing volumes to existing Storage Group
        4. List volumes of a Storage Group
      private: false
    - name: "sg_name_tocreate"
      prompt: "Enter the Storage group name that you want to create"
      private: false
    - name: "user_volume_name"
      prompt: "Enter the Volume name that you want to create"
      private: false
