- name: Volume operations on VMAX
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  roles:
    - role: volume_role

  vars_prompt:
    - name: user_input
      prompt: |
        Please select an action:
        1. Create a volume
        2. Rename volume
        3. Delete volume
      private: false
  vars_files:
    - vault.yml
