- name: Create a new Storage Group with error handling
  block:
    - name: Create a new Storage Group
      dellemc.powermax.storagegroup:
        unispherehost: "{{ unispherehost }}"
        universion: "{{ universion }}"
        verifycert: "{{ verifycert }}"
        user: "{{ user }}"
        password: "{{ password }}"
        serial_no: "{{ serial_no }}"
        sg_name: "{{ sg_name }}"
        service_level: "{{ service_level }}"
        srp: "{{ srp }}"
        compression: true
        state: "present"
      register: sg_result

    - name: Show the result of Storage Group creation
      ansible.builtin.debug:
        var: sg_result

    - name: Show success message
      ansible.builtin.debug:
        msg: "Successfully created Storage Group '{{ sg_name }}' with Service Level '{{ service_level }}'."
      when: sg_result is succeeded and sg_result.changed | default(false)

    - name: Show no change message
      ansible.builtin.debug:
        msg: "Storage Group '{{ sg_name }}' already exists with the specified configuration."
      when: sg_result is succeeded and not sg_result.changed | default(true)

  rescue:
    - name: Show failure message
      ansible.builtin.debug:
        msg: "Failed to create Storage Group '{{ sg_name }}'. Check logs for details."

  always:
    - name: Ensure the task completes cleanly
      ansible.builtin.debug:
        msg: " Storage Group creation process completed."
