- name: Create new volumes for existing Storage Group
  block:
    - name: Create new volume
      dellemc.powermax.storagegroup:
        unispherehost: "{{ unispherehost }}"
        universion: "{{ universion }}"
        verifycert: "{{ verifycert }}"
        user: "{{ user }}"
        password: "{{ password }}"
        serial_no: "{{ serial_no }}"
        sg_name: "{{ sg_name }}"
        state: "present"
        volumes:
          - vol_name: "{{ vol_name }}"
            size: "{{ size }}"
        vol_state: "present-in-group"
      register: sg_result

    - name: Show success message
      ansible.builtin.debug:
        msg: >-
          Volume '{{ vol_name }}' with size ({{ size }} GB) is now in Storage Group '{{ sg_name }}'.
          {% if sg_result.changed %} New volume created. {% else %} Volume already exists and was not modified. {% endif %}
      when: sg_result is not failed

  rescue:
    - name: Handle volume creation failure
      ansible.builtin.debug:
        msg: " Failed to create volume '{{ vol_name }}'. Error: {{ sg_result.msg }}"
