- name: Create new volumes for existing Storage Group
  dellemc.powermax.storagegroup:
    unispherehost: "{{ unispherehost }}"
    universion: "{{ universion }}"
    verifycert: "{{ verifycert }}"
    user: "{{ user }}"
    password: "{{ password }}"
    serial_no: "{{ serial_no }}"
    sg_name: "{{ sg_name }}"
    state: "present"
    volumes:
      - vol_name: "{{ vol_name }}"
        size: " {{ size }}"
    vol_state: "present-in-group"
  register: sg_result
