- name: Rename volume
  dellemc.powermax.volume:
    unispherehost: "{{ unispherehost }}"
    universion: "{{ universion }}"
    verifycert: "{{ verifycert }}"
    user: "{{ user }}"
    password: "{{ password }}"
    serial_no: "{{ serial_no }}"
    new_name: "{{ new_name }}"  # Desired new volume name
    vol_id: "{{ vol_id }}"
    state: "present"  # Ensures the volume is in the "present" state, effectively renaming it

  register: rename_result

- name: Debug the renamed volume details
  ansible.builtin.debug:
    msg: "Renamed volume details: {{ rename_result }}"
